master:
 image: jenkins/jenkins
 imageTag: lts-jdk11

 cpu: "1000m"
 memory: "4Gi"
 serviceType: ClusterIP

 #hostName: jenkins.192.168.1.190.nip.io
agent:
 image: jenkins/jnlp-slave
 imageTag: latest-jdk11
rbac:
 create: true
