
#java-build

apiVersion: v1
kind: Namespace
metadata:
  name: java-build

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: java-build

---

# jenkins rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-jenkins-role-binding
  namespace: java-build
  labels:
    app: java-jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: java-jenkins
  namespace: java-jenkins

---
#build rolebinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: build
  namespace: java-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: build

---

#java namespace
apiVersion: v1
kind: Namespace
metadata:
  name: java

---
#build role binding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: build
  namespace: java
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: build
  namespace: java-build

---

#java-jenkins
apiVersion: v1
kind: Namespace
metadata:
  name: java-jenkins

---
# jenkins rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-jenkins-role-binding
  namespace: java-jenkins
  labels:
    app: java-jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: java-jenkins
  namespace: java-jenkins

